#' Collate ontologies
#'
#' Collate cluster names according to their mapped cell ontology,
#' in order to determine the consistency of ontology mappings across datasets.
#'
#' @param paths Character vector containing directories generated by Analytical Biosciences,
#' where each directory contains files pertaining to a single part of a dataset.
#'
#' @return A list of data.frames.
#' Each data.frame corresponds to a single cell ontology term and contains all cluster names (and their dataset IDs) mapping to that ontology.
#'
#' @author Aaron Lun
#'
#' @export
#' @importFrom utils read.delim
collateOntologies <- function(paths) {
    collected <- list()
    for (x in seq_along(paths)) {
        ontfile <- file.path(paths[x], "ontologyMapping.tsv")
        if (!file.exists(ontfile)) {
            next
        }

        ont <- read.delim(ontfile, na.strings=NULL, stringsAsFactors=FALSE, colClasses="character")
        meta <- read.delim(file.path(paths[x], "metadata.tsv"), stringsAsFactors=FALSE)
        ont$datasetID <- as.character(meta$datasetID)
        collected[[x]] <- ont
    }

    combined <- do.call(rbind, collected)
    split(combined[,c("cellOntologyName", "clusterName", "datasetID")], combined$cellOntologyID)
}
