#' Generate MTX files according to the RDS files in each dataset.
#'
#' @param paths Character vector containing directories generated by Analytical Biosciences,
#' where each directory contains files pertaining to a single part of a dataset.
#'
#' @return A vector of MTX file names that is successfully converted from RDS files.
#'
#' @author Analytical Biosciences
#'
#' @export
#' @importFrom Matrix writeMM
generateMTX <- function(paths) {
    MTXfiles = c()
    files <- list.files(paths, pattern = ".rds")
    for (x in files) {
        RDSfile = readRDS(file.path(paths, x))
        writeMM(RDSfile, file.path(paths, sub(".rds",".mtx",x)))
        MTXfiles = c(MTXfiles, sub(".rds",".mtx",x))
    }
    return(MTXfiles)
}




