#' Load marker sets
#'
#' Load marker sets generated by Analytical Biosciences as a \linkS4class{List} of \linkS4class{DataFrame}s in R.
#'
#' @param dir String containing a path to a directory of files
#' generated by Analytical Biosciences.
#'
#' @return A \linkS4class{List} of \linkS4class{DataFrame}s where each DataFrame contains ranked marker genes for each cluster in the study.
#'
#' @author Aaron Lun
#'
#' @details
#' This ingests the marker list to create a list of ranking tables, which will serve as the basis of any upload to Genentech systems.
#' If no marker list exists, an empty \linkS4class{List} is returned.
#'
#' @examples
#' \dontrun{
#' sce <- loadMarkers("No_1/part_1")
#' }
#'
#' @export
#' @importFrom S4Vectors DataFrame List
#' @importMethodsFrom S4Vectors split
loadMarkers <- function(dir) {
    fname <- file.path(dir, "markerGenes.tsv")
    if (!file.exists(fname)) {
        return(List())
    }

    all.sets <- read.delim(fname, stringsAsFactors=FALSE)
    by <- which(colnames(all.sets)=="clusterName")

    stopifnot(length(by)==1L)
    stopifnot(is.numeric(all.sets$pValue))

    all.sets <- DataFrame(all.sets)
    output <- split(all.sets[,-by], all.sets[,by])

    for (i in seq_along(output)) {
        stopifnot(!is.unsorted(output[[i]]$pValue))
    }

    output
}
