#' Compile a per-study report
#'
#' Compile a Rmarkdown report summarizing a single study of scRNA-seq data,
#' from a directory of files prepared by Analytical Biosciences.
#'
#' @param dir String containing a path to a directory of files
#' generated by Analytical Biosciences.
#' @param fname String containing the output name of the Rmarkdown report. 
#'
#' @return An Rmarkdown report is produced at \code{fname} and compiled with \code{\link{render}}.
#'
#' @details 
#' The Rmarkdown report simply calls \code{\link{createSCE}} and \code{\link{loadMarkers}}
#' to check that the various files in \code{dir} can, in fact, be read into R data structures.
#'
#' It will then give a preview of each of the data fields in these objects,
#' allowing readers to inspect the contents of the files in an efficient manner.
#'
#' @author Aaron Lun
#'
#' @examples
#' \dontrun{
#' perStudyReport("No_1/part_1")
#' }
#' @export
#' @importFrom rmarkdown render
perStudyReport <- function(dir, fname="report.Rmd") {
    template <- system.file("scripts", "per-study.Rmd", package="abscd")
    input <- readLines(template)
    write(sub("INSERT_DIR_HERE", deparse(dir), input), file=fname)
    render(fname)
}
